name: StoreScreenshot
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  store-screenshot-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      actions: read
      contents: write
      repository-projects: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Record Screenshot
        id: record-test
        run: |
          ./gradlew recordRoborazziDebug --stacktrace --rerun-tasks

      - name: Upload Screenshot
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: screenshot
          path: |
            **/build/outputs/roborazzi
          retention-days: 30

      - name: Upload Screenshot Reports
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: screenshot-reports
          path: |
            **/build/reports
          retention-days: 30

      - name: Upload Screenshot Test Results
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: screenshot-test-results
          path: |
            **/build/test-results
          retention-days: 30

      - name: update PR description
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DESCRIPTION=$(gh pr view ${{ github.event.pull_request.number }} --json body --jq .body)
          gh pr edit ${{ github.event.pull_request.number }} --body  "AAAAAAAA
          ---
          ${DESCRIPTION}"